#!/usr/bin/env mksh
# === {{CMD}}  dev|prod|www

local +x PATH="$PATH:$THIS_DIR/../my_crystal/bin"
if [[ -z "$@" ]]; then
  local +x TARGET="dev"
else
  local +x TARGET="$1"; shift
fi

cd "$THIS_DIR"
mkdir -p tmp/out
mkdir -p prod

sh_color YELLOW "=== Compiling: {{${TARGET}}} ..."


case "$TARGET" in
  dev)
    my_crystal __ build src/megauni/server.cr -o tmp/out/${APP_NAME}.tmp
    mv tmp/out/${APP_NAME}.tmp tmp/out/server
    exit 0
    ;;

  prod)
    my_crystal __ build --release src/${APP_NAME}.cr
    ;;

  *)
    echo "!!! Invalid option: $TARGET" >&2
    exit 2
    ;;
esac

if [[ -f "$APP_NAME" ]]; then
  mv ${APP_NAME} tmp/${APP_NAME}
  echo "=== Created: tmp/${APP_NAME}" >&2
fi

sh_color GREEN "=== Done: {{compile $TARGET}}"

