#!/usr/bin/env mksh
# === {{CMD}}  dev|prod|www

local +x PATH="$PATH:$THIS_DIR/../my_crystal/bin"
local +x TARGET="$1"; shift
cd "$THIS_DIR"
mkdir -p tmp
mkdir -p prod

sh_color YELLOW "=== Compiling: {{${TARGET}}} ..."

if command -v crystal &>/dev/null ; then
  local +x CRYSTAL="crystal"
else
  local +x CRYSTAL="my_crystal"
fi

case "$TARGET" in
  www)
    "$CRYSTAL" build compile/www.cr -o tmp/www
    exit 0
    ;;

  prod)
    "$CRYSTAL" build --release src/${APP_NAME}.cr
    ;;

  *)
    echo "!!! Invalid option: $TARGET" >&2
    exit 2
    ;;
esac

if [[ -f "$APP_NAME" ]]; then
  mv ${APP_NAME} tmp/${APP_NAME}
  echo "=== Created: tmp/${APP_NAME}" >&2
fi

sh_color GREEN "=== Done: {{compile $TARGET}}"

