#!/usr/bin/env mksh

# === {{CMD}}
cd "$THIS_DIR"
sh_color ORANGE "=== {{Pulling}} from: $(git remote get-url origin)"
git pull

sh_color ORANGE "=== {{Upgrading}}: yarn upgrade"
yarn upgrade

sh_color ORANGE "=== {{Upgrading}}: Crystal deps"
my_crystal __ deps update

sh_color ORANGE "=== {{Compiling}}: static assets"
megauni.cr dev static

sh_color GREEN "=== {{Done upgrading}}."
