#!/bin/sh
# === Sample runit "run" file.


exec 2>&1
set -u -e

PREFIX="/apps/megauni/postgresql-10.4"

export PGROOT="$PREFIX"
export PGDATA="$PREFIX/data"
export PGLOG="$PGDATA/log.log"
export PATH="$PREFIX/bin:$PATH"

cd "$PREFIX"

# Extra options to run postmaster with, e.g.:
# -N is the maximal number of client connections
# -B is the number of shared buffers and has to be at least 2x the value for -N
echo "=== in $PWD: $(date): $(postgres --version)"
args="$@"
if [ ! -z "$args" ] ; then
  echo "=== arguments: $@"
fi

set -x
exec \
  chpst -u pg-megauni:pg-megauni \
  $PREFIX/bin/postgres \
   --config_file="/apps/megauni/config/dev/postgresql.conf" \
   --hba_file="/apps/megauni/config/dev/pg_hba.conf" \
   --data_directory="$PGDATA" \
    -N 10 -B 20 $@


