#!/usr/bin/env zsh

# === {{CMD}} dev
# === {{CMD}} grace|stop|quit
local +x cmd="megauni.cr server start"
case "$@" in

  is-running)
    if pgrep -f "$cmd" &>/dev/null; then
      exit 0
    fi
    exit 1
    ;;

  is-stopped)
    if megauni.cr server is-running &>/dev/null; then
      exit 1
    fi
    exit 0
    ;;

  grace|stop|quit)
    if ! megauni.cr server is-running ; then
      sh_color ORANGE "=== No {{server}} found."
    else
      local +x pid="$( pgrep -f "$cmd" || : )"

      if [[ -z "$pid" ]]; then
        sh_color ORANGE "=== No {{server}} found."
        exit 0
      fi

      if [[ "$(echo "$pid" | wc -l)" -gt "1" ]]; then
        sh_color RED "!!! Too many server pids found."
        exit 2
      fi

      for cpid in $(process child-pids $pid); do
        kill -TERM ${cpid} || {
          stat="$?"
          sh_color RED "!!! Could not kill -$cpid. Exited: $stat"
        }
      done
      kill -TERM $pid

      process loop every 1 max 10 or until megauni.cr server is-stopped
      if megauni.cr server is-running ; then
        echo "=== Could not pkill: $cmd";
      fi
    fi
    ;;

  start)
    if [[ -z "$IS_DEV" ]]; then
      sh_color RED "!!! server binary not found."
      exit 2
    else
      HTTP_SERVER_SESSION_SECRET="$(date)$(date)" tmp/out/server
    fi
    ;;

  *)
    echo "!!! Invalid option: $@" >&2
    exit 2
    ;;

esac
