#!/usr/bin/env mksh

# === {{CMD}} dev
# === {{CMD}} grace
case "$@" in

  grace)
    local +x cmd="tmp/$APP_NAME"
    pkill -f "$cmd" || :
    if pgrep $cmd ; then
      echo "=== Could not pkill: $cmd";
    fi
    ;;

  dev!)
    rm -f "tmp/out/megauni"
    megauni.cr server dev
    ;;

  dev)
    if [[ ! -f "tmp/out/megauni" ]]; then
      megauni.cr compile dev
    fi
    sh_color YELLOW "=== Running server: {{$@}} ..."
    tmp/out/megauni
    ;;

  *)
    echo "!!! Invalid option: $@" >&2
    exit 2
    ;;

esac
