#!/usr/bin/env zsh

# === {{CMD}}  watch|run
# === Used soley for development.
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in
  run)
    $APP_NAME server grace
    $APP_NAME compile dev
    $APP_NAME server dev &
    ;;

  watch)
    $APP_NAME watch run $ARGS || :
    process watch "-r src -r bin -r spec -r compile" "$APP_NAME watch run"
    ;;

  *)
    sh_color RED "=== Unknown command: {{$ACTION $@}}"
    exit 2
    ;;
esac

