#!/usr/bin/env mksh

# === {{CMD}}
# === {{CMD}}  dev|prod|www
case "$@" in
  "run "*)
    shift
    case "$@" in
      "www")
        $APP_NAME compile www
        sh_color YELLOW "=== Running: {{tmp/www}} ..."
        tmp/www
        ;;

      "dev")
        $APP_NAME server grace
        $APP_NAME compile dev
        $APP_NAME server dev &
        ;; 

      *)
        sh_color RED "!!! {{Invalid option given}} for run: $@"
        exit 2
        ;;
    esac
    ;;

  *)
    local +x ARGS="$(echo $@)"
    ARGS="${ARGS:-dev}"

    $APP_NAME watch run $ARGS || :
    mksh_setup watch \
      "-r src -r bin -r spec -r compile" \
      "$APP_NAME watch run $ARGS"
    ;;
esac

