#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

if [[ -z "${IS_DEV:-}" ]]; then
  sh_color RED "!!! Run only on a {{DEV}} machine."
  exit 2
fi

cd "$THIS_DIR"
mkdir -p tmp/in tmp/out

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
local +x ACTION="watch"
else
  local +x ACTION=$1; shift
fi

case "$ACTION" in

  watch)
    cd "$THIS_DIR"
    local +x CMD="megauni.cr specs run $@"
    ${=CMD} || :
    process watch "-r ./" "$CMD"
    ;;

  restart-server)
    reset
    if megauni.cr server is-running ; then
      sh_color ORANGE "=== {{Stopping}} server..."
      megauni.cr server stop
    fi
    sh_color ORANGE "=== {{Running}} server..."
    ( megauni.cr server start ) &
    sleep 1
    curl http://localhost:3000/
    echo "====================="
    ;;

  run)
    reset
    cd "$THIS_DIR"
    case "${CHANGED_FILE:-any.cr}" in
      *shard.yml*)
        sh_color ORANGE "=== Updating {{crystal deps}}..."
        my_crystal __ deps update
        ;;

      # *"/_")
      #   CHANGED_FILE=any.cr megauni.cr specs run
      #   ;;

      # *".cr")
      #   sh_color ORANGE "=== {{Compiling}} server..."
      #   SERVER="yes" my_crystal __ build src/megauni/server.cr -o tmp/out/server
      #   megauni.cr specs restart-server
      #   ;;

      # *.html)
      #   megauni.cr specs restart-server
      #   ;;

      # *)
      #   sh_color ORANGE "=== Don't know what to do about file: $CHANGED_FILE"
      #   ;;
    esac

    sh_color ORANGE "=== {{Compiling}}..."
    INCLUDE_SPECS=yes INCLUDE_SERVER=yes my_crystal __ build src/megauni.cr -o tmp/out/specs

    sh_color ORANGE "=== {{Running}}..."
    RUN_SPECS=yes tmp/out/specs $(cat tmp/in/args 2>/dev/null || :)
    sh_color GREEN "=== {{DONE}} running specs === "
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac


