#!/usr/bin/env zsh

# === {{CMD}}  watch|run
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in
  css)
    sh_color ORANGE "=== {{Compiling}} css..."
    CSS_COMPILE="yes" my_crystal __ build src/megauni.cr -o tmp/out/megauni.static.css
    tmp/out/megauni.static.css
    ;;

  html)
    sh_color ORANGE "=== {{Compiling}} html..."
    HTML_COMPILE="yes" my_crystal __ build src/megauni.cr -o tmp/out/megauni.static.html
    tmp/out/megauni.static.html
    ;;

  js)
    sh_color ORANGE "=== {{Compiling}} js..."
    my_jspp __ src/megauni/model/root/main.jspp node_modules/da_standard/src/*.jspp -o Public/root/main.js
    ;;

  static)
    megauni.cr dev css
    megauni.cr dev html
    megauni.cr dev js
    ;;

  run)
    reset
    mkdir -p tmp/in tmp/out

    megauni.cr dev html
    return 0

    sh_color ORANGE "=== {{Compiling}} static assets..."
    megauni.cr dev static

    sh_color ORANGE "=== {{Compiling}} server..."
    DEVELOPMENT=yes my_crystal __ build src/megauni/server.cr -o tmp/out/megauni.server

    sh_color ORANGE "=== {{Terminating}} previous server..."
    pkill -f "tmp/out/megauni.server" || :

    sh_color ORANGE "=== {{Running}}..."
    HTTP_SERVER_SESSION_SECRET="0x340x46nasfiermoe$(date +%s)" tmp/out/megauni.server &
    process loop every 1 max 4 or until "my_network url-is-up http://localhost:3000/" &>/dev/null
    {
      my_network inspect "http://localhost:3000/"
      my_network inspect "http://localhost:3000/megauni/files/root/main.css"
      my_network inspect "http://localhost:3000/megauni/files/root/main.js"
    } | grep -P 'localhost|HTTP'
    ;;

  watch)
    local +x CMD="$APP_NAME dev run"
    ${=CMD} || :
    process watch "-r src -r bin -r sh -r specs" "$CMD"
    ;;

  *)
    sh_color RED "=== Unknown command: {{$ACTION $@}}"
    exit 2
    ;;
esac


