#!/usr/bin/env zsh

# === {{CMD}}  watch|run
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in
  run)
    reset
    mkdir -p tmp/in tmp/out

    sh_color ORANGE "=== {{Compiling}}..."
    my_crystal __ build src/server.cr -o tmp/out/megauni.server

    sh_color ORANGE "=== {{Terminating}} previous server..."
    pkill -f "tmp/out/megauni.server" || :

    sh_color ORANGE "=== {{Running}}..."
    tmp/out/megauni.server &
    my_network inspect "http://localhost:3000/"
    ;;

  watch)
    local +x CMD="$APP_NAME dev run"
    ${=CMD} || :
    process watch "-r src -r bin -r sh -r specs" "$CMD"
    ;;

  *)
    sh_color RED "=== Unknown command: {{$ACTION $@}}"
    exit 2
    ;;
esac

